spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.lim.redisdb.domain
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  level:
    com.lim.redisdb: debug
    org.springframework.data.redis: debug